const initialWordsList = [
    { id: "1", content: "crisp", position: { x: 0, y: 0 } },
    { id: "2", content: "jagged", position: { x: 50, y: 0 } },
    { id: "3", content: "murky", position: { x: 100, y: 0 } },
    { id: "4", content: "sly", position: { x: 150, y: 0 } },
    { id: "5", content: "velvet", position: { x: 200, y: 0 } },
    { id: "6", content: "merrily", position: { x: 250, y: 0 } },
    { id: "7", content: "coyly", position: { x: 300, y: 0 } },
    { id: "8", content: "sternly", position: { x: 350, y: 0 } },
    { id: "9", content: "vividly", position: { x: 400, y: 0 } },
    { id: "10", content: "hastily", position: { x: 450, y: 0 } },
    { id: "11", content: "whereas", position: { x: 500, y: 0 } },
    { id: "12", content: "yet", position: { x: 550, y: 0 } },
    { id: "13", content: "though", position: { x: 600, y: 0 } },
    { id: "14", content: "until", position: { x: 650, y: 0 } },
    { id: "15", content: "unless", position: { x: 700, y: 0 } },
    { id: "16", content: "the", position: { x: 750, y: 0 } },
    { id: "17", content: "a", position: { x: 800, y: 0 } },
    { id: "18", content: "an", position: { x: 850, y: 0 } },
    { id: "19", content: "these", position: { x: 900, y: 0 } },
    { id: "20", content: "every", position: { x: 950, y: 0 } },
    { id: "21", content: "lantern", position: { x: 1000, y: 0 } },
    { id: "22", content: "echo", position: { x: 1050, y: 0 } },
    { id: "23", content: "meadow", position: { x: 1100, y: 0 } },
    { id: "24", content: "puzzle", position: { x: 1150, y: 0 } },
    { id: "25", content: "gust", position: { x: 1200, y: 0 } },
    { id: "26", content: "beneath", position: { x: 1250, y: 0 } },
    { id: "27", content: "amid", position: { x: 1300, y: 0 } },
    { id: "28", content: "beyond", position: { x: 1350, y: 0 } },
    { id: "29", content: "within", position: { x: 1400, y: 0 } },
    { id: "30", content: "opposite", position: { x: 1450, y: 0 } },
    { id: "31", content: "we", position: { x: 1500, y: 0 } },
    { id: "32", content: "they", position: { x: 1550, y: 0 } },
    { id: "33", content: "it", position: { x: 1600, y: 0 } },
    { id: "34", content: "you", position: { x: 1650, y: 0 } },
    { id: "35", content: "her", position: { x: 1700, y: 0 } },
    { id: "36", content: "glimmers", position: { x: 1750, y: 0 } },
    { id: "37", content: "wavers", position: { x: 1800, y: 0 } },
    { id: "38", content: "whispers", position: { x: 1850, y: 0 } },
    { id: "39", content: "twitches", position: { x: 1900, y: 0 } },
    { id: "40", content: "stumbles", position: { x: 1950, y: 0 } },
    { id: "41", content: ".", position: { x: 2000, y: 0 } },
    { id: "42", content: ".", position: { x: 2050, y: 0 } },
    { id: "43", content: ".", position: { x: 2100, y: 0 } },
    { id: "44", content: ".", position: { x: 2150, y: 0 } },
    { id: "45", content: ".", position: { x: 2200, y: 0 } },
    { id: "46", content: ",", position: { x: 2250, y: 0 } },
    { id: "47", content: ",", position: { x: 2300, y: 0 } },
    { id: "48", content: ",", position: { x: 2350, y: 0 } },
    { id: "49", content: ",", position: { x: 2400, y: 0 } },
    { id: "50", content: ",", position: { x: 2450, y: 0 } }
  ];
  
  export default initialWordsList;
  